"""
Fix recommender for InspectAI.

Takes AnalysisResult from the failure analyzer and generates
three types of concrete fixes for each failure pattern:

Fix Type 1 — PROMPT_ADDITION
  Suggested text to add to the system prompt.
  Clearly labeled as a suggestion — not the exact prompt.
  Company reviews and adapts to their actual system.

Fix Type 2 — GUARDRAIL_RULE
  Specific input/output filtering rule.
  Catches the failure pattern at runtime before it reaches users.

Fix Type 3 — FINE_TUNING_DATA
  References training pairs generated by the learning engine.
  Company downloads as JSONL and fine-tunes their open-source model.

Fix Type 4 — ARCHITECTURE_CHANGE (RAG systems only)
  Structural recommendations — retrieval strategy, reranking,
  context window size, chunk overlap.

Fix Type 5 — POLICY_CLARIFICATION
  When the failure is because the policy itself is ambiguous.
  Recommends clarifying the policy before fixing the AI.

All fixes clearly labeled as suggestions.
Company decides priority and which fixes to implement.
"""

from __future__ import annotations

import asyncio
import json

import litellm
import structlog

from inspectai.analyzers.failure_analyzer import AnalysisResult, FailurePattern
from inspectai.config import settings
from inspectai.core.learning_engine import LearningEngine
from inspectai.models.schemas import (
    DetailedFixRecommendation,
    FailureType,
    FixRecommendationReport,
    FixType,
    InspectAILearning,
    Priority,
    SystemConfig,
    SystemType,
)

logger = structlog.get_logger()

LLM_TIMEOUT = 30
COST_PER_1K_TOKENS = 0.003

DEFAULT_FIX_PRIORITY = {
    FailureType.POLICY_VIOLATION: Priority.HIGH,
    FailureType.ESCALATION_FAILURE: Priority.HIGH,
    FailureType.HALLUCINATION: Priority.HIGH,
    FailureType.WRONG_ANSWER: Priority.MEDIUM,
    FailureType.INCOMPLETE: Priority.MEDIUM,
    FailureType.CONTEXT_LOSS: Priority.LOW,
}


class FixRecommender:
    """
    Generates concrete fix recommendations from failure analysis.

    Usage:
        recommender = FixRecommender()
        report = await recommender.recommend(
            analysis=analysis,
            config=config,
            learning=learning,
        )
    """

    def __init__(self, model: str | None = None) -> None:
        self.model = model or settings.default_model
        self._cost = 0.0
        self._learning_engine = LearningEngine()

    async def recommend(
        self,
        analysis: AnalysisResult,
        config: SystemConfig | None = None,
        learning: InspectAILearning | None = None,
    ) -> FixRecommendationReport:
        """
        Main entry point. Generates all applicable fix types
        for every failure pattern found in analysis.
        Returns FixRecommendationReport with full fix list.
        """
        self._cost = 0.0

        company_name = "the system"
        if config:
            active = config.get_active_config()
            if active:
                company_name = getattr(active, "company_name", "the system")

        if not analysis.failure_patterns:
            logger.info(
                "no_failure_patterns_to_fix",
                company=company_name,
                pass_rate=analysis.test_run.pass_rate,
            )
            return FixRecommendationReport(
                system_type=analysis.test_run.system_type,
                company_name=company_name,
                pass_rate=analysis.test_run.pass_rate,
                total_failures=analysis.test_run.failed,
                total_fixes=0,
                estimated_improvement=(
                    "No failures detected — system performing well"
                ),
            )

        logger.info(
            "fix_recommendation_started",
            company=company_name,
            patterns=len(analysis.failure_patterns),
            pass_rate=analysis.test_run.pass_rate,
        )

        fix_tasks = [
            self._generate_fixes_for_pattern(
                pattern=pattern,
                config=config,
                analysis=analysis,
            )
            for pattern in analysis.failure_patterns
        ]

        fix_results = await asyncio.gather(*fix_tasks, return_exceptions=True)

        all_fixes: list[DetailedFixRecommendation] = []
        for result in fix_results:
            if isinstance(result, Exception):
                logger.error("fix_generation_failed", error=str(result))
            elif isinstance(result, list):
                all_fixes.extend(result)

        # Add fine-tuning data reference if learning available
        fine_tuning_count = 0
        if learning and config:
            fine_tuning_pairs = self._learning_engine.export_finetuning_data(
                learning=learning,
                config=config,
                format="jsonl",
            )
            fine_tuning_count = (
                fine_tuning_pairs.count("\n") + 1 if fine_tuning_pairs else 0
            )

            if fine_tuning_count > 0:
                all_fixes.append(
                    self._create_fine_tuning_fix(
                        count=fine_tuning_count,
                        analysis=analysis,
                    )
                )

        # Sort — HIGH priority first, then by affected scenarios descending
        all_fixes.sort(
            key=lambda f: (
                0 if f.suggested_priority == Priority.HIGH else
                1 if f.suggested_priority == Priority.MEDIUM else 2,
                -f.affected_scenarios,
            )
        )

        estimated_improvement = await self._estimate_improvement(
            analysis=analysis,
            fixes=all_fixes,
            company_name=company_name,
        )

        report = FixRecommendationReport(
            system_type=analysis.test_run.system_type,
            company_name=company_name,
            pass_rate=analysis.test_run.pass_rate,
            total_failures=analysis.test_run.failed,
            total_fixes=len(all_fixes),
            fixes=all_fixes,
            estimated_improvement=estimated_improvement,
            high_priority_count=sum(
                1 for f in all_fixes if f.suggested_priority == Priority.HIGH
            ),
            medium_priority_count=sum(
                1 for f in all_fixes if f.suggested_priority == Priority.MEDIUM
            ),
            low_priority_count=sum(
                1 for f in all_fixes if f.suggested_priority == Priority.LOW
            ),
            fine_tuning_pairs_available=fine_tuning_count,
            generation_cost_usd=self._cost,
        )

        logger.info(
            "fix_recommendation_complete",
            total_fixes=len(all_fixes),
            high_priority=report.high_priority_count,
            medium_priority=report.medium_priority_count,
            low_priority=report.low_priority_count,
            fine_tuning_available=fine_tuning_count,
            cost=self._cost,
        )

        return report

    # ─── Private: generate all fixes for one pattern ──────────────

    async def _generate_fixes_for_pattern(
        self,
        pattern: FailurePattern,
        config: SystemConfig | None,
        analysis: AnalysisResult,
    ) -> list[DetailedFixRecommendation]:
        """
        Generates all applicable fix types for one failure pattern.
        Runs prompt, guardrail, and architecture fixes concurrently.
        """
        tasks = [
            self._generate_prompt_fix(pattern, config),
            self._generate_guardrail_fix(pattern, config),
        ]

        if config and config.system_type == SystemType.RAG:
            tasks.append(self._generate_architecture_fix(pattern, config))

        if pattern.failure_type == FailureType.POLICY_VIOLATION:
            tasks.append(
                self._generate_policy_clarification(pattern, config)
            )

        results = await asyncio.gather(*tasks, return_exceptions=True)

        fixes = []
        for result in results:
            if isinstance(result, Exception):
                logger.warning(
                    "fix_type_failed",
                    pattern=pattern.cluster_label,
                    error=str(result),
                )
            elif result is not None:
                fixes.append(result)

        return fixes

    # ─── Private: prompt addition fix ─────────────────────────────

    async def _generate_prompt_fix(
        self,
        pattern: FailurePattern,
        config: SystemConfig | None,
    ) -> DetailedFixRecommendation | None:
        """
        Generates a suggested prompt addition for a failure pattern.
        Clearly labeled as suggestion — company adapts to their system.
        """
        company_name = "the system"
        system_type = "AI system"
        policy_context = ""

        if config:
            active = config.get_active_config()
            if active:
                company_name = getattr(active, "company_name", "the system")
                system_type = (
                    config.system_type.value.lower().replace("_", " ")
                )
                policy_lines = []
                if hasattr(active, "escalation"):
                    esc = active.escalation
                    if esc.refund_threshold:
                        policy_lines.append(
                            f"Refund threshold: ${esc.refund_threshold}"
                        )
                    if esc.escalate_on_keywords:
                        policy_lines.append(
                            f"Escalation keywords: {esc.escalate_on_keywords}"
                        )
                if policy_lines:
                    policy_context = "\n".join(policy_lines)

        prompt = f"""You are generating a system prompt improvement suggestion
for a {system_type} called {company_name}.

FAILURE PATTERN FOUND:
Type: {pattern.failure_type.value}
Cluster label: {pattern.cluster_label}
Affected scenarios: {pattern.scenario_count}
Root cause: {pattern.root_cause}
Evidence: {pattern.evidence}
Example failures:
{chr(10).join(f"- {ex[:100]}" for ex in pattern.example_inputs[:3])}

{f"KNOWN POLICIES:{chr(10)}{policy_context}" if policy_context else ""}

Generate a suggested PROMPT ADDITION that would help address this failure.

IMPORTANT RULES:
1. You do NOT know the company's actual system prompt
2. Generate a suggested ADDITION or pattern — not a full prompt rewrite
3. Be specific — reference the exact failure type and condition
4. Keep it concise — 2-5 sentences maximum
5. Use clear, direct language the AI can follow

Return ONLY valid JSON:
{{
  "title": "short descriptive title for this fix",
  "problem": "one sentence describing exactly what is broken",
  "suggested_fix": "the specific text to add to the system prompt",
  "implementation_steps": [
    "step 1",
    "step 2",
    "step 3"
  ],
  "verification_scenarios": [
    "scenario to test after fix",
    "another scenario to test"
  ],
  "estimated_impact": "e.g. May address ~X% of failures"
}}"""

        try:
            async with asyncio.timeout(LLM_TIMEOUT):
                response = await litellm.acompletion(
                    model=self.model,
                    messages=[{"role": "user", "content": prompt}],
                    temperature=0.3,
                    max_tokens=600,
                )

            raw = response.choices[0].message.content.strip()
            if raw.startswith("```"):
                raw = raw.split("```")[1]
                if raw.startswith("json"):
                    raw = raw[4:]
            data = json.loads(raw.strip())

            if hasattr(response, "usage") and response.usage:
                tokens = response.usage.total_tokens or 0
                self._cost += (tokens / 1000) * COST_PER_1K_TOKENS

            return DetailedFixRecommendation(
                failure_pattern=pattern.cluster_label,
                failure_type=pattern.failure_type,
                affected_scenarios=pattern.scenario_count,
                fix_type=FixType.PROMPT_ADDITION,
                title=data.get("title", "Prompt improvement suggestion"),
                problem=data.get("problem", pattern.root_cause),
                suggested_fix=data.get("suggested_fix", ""),
                implementation_steps=data.get("implementation_steps", []),
                verification_scenarios=data.get("verification_scenarios", []),
                suggested_priority=DEFAULT_FIX_PRIORITY.get(
                    pattern.failure_type, Priority.MEDIUM
                ),
                estimated_impact=data.get("estimated_impact", ""),
                disclaimer=(
                    "This is a suggested prompt addition based on observed "
                    "failures. Review and adapt to your actual system prompt "
                    "before implementing. This may not be exactly correct "
                    "for your specific setup."
                ),
            )

        except Exception as e:
            logger.error(
                "prompt_fix_generation_failed",
                pattern=pattern.cluster_label,
                error=str(e),
            )
            return None

    # ─── Private: guardrail fix ───────────────────────────────────

    async def _generate_guardrail_fix(
        self,
        pattern: FailurePattern,
        config: SystemConfig | None,
    ) -> DetailedFixRecommendation | None:
        """
        Generates a guardrail rule for a failure pattern.
        Guardrails catch failures at runtime before reaching users.
        """
        company_name = "the system"
        if config:
            active = config.get_active_config()
            if active:
                company_name = getattr(active, "company_name", "the system")

        prompt = f"""You are generating a guardrail rule suggestion
for {company_name}.

FAILURE PATTERN:
Type: {pattern.failure_type.value}
Root cause: {pattern.root_cause}
Evidence: {pattern.evidence}
Example failures:
{chr(10).join(f"- {ex[:100]}" for ex in pattern.example_inputs[:3])}

Generate a GUARDRAIL RULE that catches this failure at runtime.
A guardrail is a filter that checks the AI response BEFORE
it is shown to the user.

Return ONLY valid JSON:
{{
  "title": "short descriptive title",
  "problem": "what this guardrail prevents",
  "suggested_fix": "the specific guardrail rule — what to check and what to do",
  "implementation_steps": [
    "step 1 — where to add this in your pipeline",
    "step 2 — what to check",
    "step 3 — what to do on trigger"
  ],
  "verification_scenarios": [
    "scenario that should be caught by guardrail",
    "scenario that should pass through"
  ],
  "estimated_impact": "e.g. Catches ~X% of this failure type at runtime"
}}"""

        try:
            async with asyncio.timeout(LLM_TIMEOUT):
                response = await litellm.acompletion(
                    model=self.model,
                    messages=[{"role": "user", "content": prompt}],
                    temperature=0.3,
                    max_tokens=500,
                )

            raw = response.choices[0].message.content.strip()
            if raw.startswith("```"):
                raw = raw.split("```")[1]
                if raw.startswith("json"):
                    raw = raw[4:]
            data = json.loads(raw.strip())

            if hasattr(response, "usage") and response.usage:
                tokens = response.usage.total_tokens or 0
                self._cost += (tokens / 1000) * COST_PER_1K_TOKENS

            return DetailedFixRecommendation(
                failure_pattern=pattern.cluster_label,
                failure_type=pattern.failure_type,
                affected_scenarios=pattern.scenario_count,
                fix_type=FixType.GUARDRAIL_RULE,
                title=data.get("title", "Guardrail rule suggestion"),
                problem=data.get("problem", pattern.root_cause),
                suggested_fix=data.get("suggested_fix", ""),
                implementation_steps=data.get("implementation_steps", []),
                verification_scenarios=data.get("verification_scenarios", []),
                suggested_priority=DEFAULT_FIX_PRIORITY.get(
                    pattern.failure_type, Priority.MEDIUM
                ),
                estimated_impact=data.get("estimated_impact", ""),
                disclaimer=(
                    "This guardrail suggestion is based on observed failure "
                    "patterns. Adapt the specific conditions and thresholds "
                    "to match your actual system architecture."
                ),
            )

        except Exception as e:
            logger.error(
                "guardrail_fix_generation_failed",
                pattern=pattern.cluster_label,
                error=str(e),
            )
            return None

    # ─── Private: architecture fix (RAG only) ─────────────────────

    async def _generate_architecture_fix(
        self,
        pattern: FailurePattern,
        config: SystemConfig | None,
    ) -> DetailedFixRecommendation | None:
        """
        Generates architectural improvement suggestions for RAG systems.
        Covers retrieval strategy, reranking, chunk size, context window.
        """
        retrieval_context = ""
        if config:
            active = config.get_active_config()
            if active and hasattr(active, "retrieval"):
                r = active.retrieval
                retrieval_context = (
                    f"Current strategy: {r.retrieval_strategy}\n"
                    f"Top-k: {r.top_k}\n"
                    f"Confidence threshold: {r.confidence_threshold}\n"
                    f"Reranking enabled: {r.reranking_enabled}"
                )

        prompt = f"""You are generating a RAG architecture improvement suggestion.

FAILURE PATTERN:
Type: {pattern.failure_type.value}
Root cause: {pattern.root_cause}
Evidence: {pattern.evidence}

{f"CURRENT RETRIEVAL CONFIG:{chr(10)}{retrieval_context}" if retrieval_context else ""}

Generate an ARCHITECTURE CHANGE suggestion to address this failure.
Focus on retrieval strategy, chunking, reranking, or context window.

Return ONLY valid JSON:
{{
  "title": "short descriptive title",
  "problem": "what architectural issue causes this failure",
  "suggested_fix": "specific architectural change to make",
  "implementation_steps": [
    "step 1",
    "step 2"
  ],
  "verification_scenarios": [
    "test after implementing"
  ],
  "estimated_impact": "expected improvement"
}}"""

        try:
            async with asyncio.timeout(LLM_TIMEOUT):
                response = await litellm.acompletion(
                    model=self.model,
                    messages=[{"role": "user", "content": prompt}],
                    temperature=0.3,
                    max_tokens=500,
                )

            raw = response.choices[0].message.content.strip()
            if raw.startswith("```"):
                raw = raw.split("```")[1]
                if raw.startswith("json"):
                    raw = raw[4:]
            data = json.loads(raw.strip())

            if hasattr(response, "usage") and response.usage:
                tokens = response.usage.total_tokens or 0
                self._cost += (tokens / 1000) * COST_PER_1K_TOKENS

            return DetailedFixRecommendation(
                failure_pattern=pattern.cluster_label,
                failure_type=pattern.failure_type,
                affected_scenarios=pattern.scenario_count,
                fix_type=FixType.ARCHITECTURE_CHANGE,
                title=data.get("title", "Architecture improvement"),
                problem=data.get("problem", pattern.root_cause),
                suggested_fix=data.get("suggested_fix", ""),
                implementation_steps=data.get("implementation_steps", []),
                verification_scenarios=data.get("verification_scenarios", []),
                suggested_priority=Priority.MEDIUM,
                estimated_impact=data.get("estimated_impact", ""),
                disclaimer=(
                    "This architectural suggestion is based on observed "
                    "retrieval failures. Review with your engineering team "
                    "before implementing structural changes."
                ),
            )

        except Exception as e:
            logger.error(
                "architecture_fix_failed",
                pattern=pattern.cluster_label,
                error=str(e),
            )
            return None

    # ─── Private: policy clarification ───────────────────────────

    async def _generate_policy_clarification(
        self,
        pattern: FailurePattern,
        config: SystemConfig | None,
    ) -> DetailedFixRecommendation | None:
        """
        When failures suggest the underlying policy is ambiguous.
        Recommends clarifying the policy before fixing the AI.
        Sometimes the AI is correct and the policy needs updating.
        """
        company_name = "the company"
        if config:
            active = config.get_active_config()
            if active:
                company_name = getattr(active, "company_name", "the company")

        prompt = f"""You are analyzing whether a policy needs clarification
for {company_name}.

FAILURE PATTERN:
Type: {pattern.failure_type.value}
Root cause: {pattern.root_cause}
Evidence: {pattern.evidence}
Example failures:
{chr(10).join(f"- {ex[:100]}" for ex in pattern.example_inputs[:3])}

Sometimes AI failures happen because the underlying policy is
ambiguous — not because the AI is wrong.

Generate a POLICY CLARIFICATION suggestion.

Return ONLY valid JSON:
{{
  "title": "short descriptive title",
  "problem": "what policy ambiguity causes this failure",
  "suggested_fix": "how to clarify the policy to eliminate ambiguity",
  "implementation_steps": [
    "step 1 — review current policy wording",
    "step 2 — clarify specific ambiguous areas",
    "step 3 — update AI config after policy is clarified"
  ],
  "verification_scenarios": [
    "test scenario after policy clarification"
  ],
  "estimated_impact": "clearer policy reduces AI confusion"
}}"""

        try:
            async with asyncio.timeout(LLM_TIMEOUT):
                response = await litellm.acompletion(
                    model=self.model,
                    messages=[{"role": "user", "content": prompt}],
                    temperature=0.3,
                    max_tokens=400,
                )

            raw = response.choices[0].message.content.strip()
            if raw.startswith("```"):
                raw = raw.split("```")[1]
                if raw.startswith("json"):
                    raw = raw[4:]
            data = json.loads(raw.strip())

            if hasattr(response, "usage") and response.usage:
                tokens = response.usage.total_tokens or 0
                self._cost += (tokens / 1000) * COST_PER_1K_TOKENS

            return DetailedFixRecommendation(
                failure_pattern=pattern.cluster_label,
                failure_type=pattern.failure_type,
                affected_scenarios=pattern.scenario_count,
                fix_type=FixType.POLICY_CLARIFICATION,
                title=data.get("title", "Policy clarification needed"),
                problem=data.get("problem", pattern.root_cause),
                suggested_fix=data.get("suggested_fix", ""),
                implementation_steps=data.get("implementation_steps", []),
                verification_scenarios=data.get("verification_scenarios", []),
                suggested_priority=Priority.HIGH,
                estimated_impact=data.get("estimated_impact", ""),
                disclaimer=(
                    "This suggestion is based on observed policy-related "
                    "failures. Review with your policy and compliance teams "
                    "before making changes."
                ),
            )

        except Exception as e:
            logger.error(
                "policy_clarification_failed",
                pattern=pattern.cluster_label,
                error=str(e),
            )
            return None

    # ─── Private: fine-tuning reference ──────────────────────────

    def _create_fine_tuning_fix(
        self,
        count: int,
        analysis: AnalysisResult,
    ) -> DetailedFixRecommendation:
        """
        Creates a fine-tuning data reference fix.
        Points company to training pairs generated by the learning engine.
        """
        return DetailedFixRecommendation(
            failure_pattern="all_failures",
            failure_type=FailureType.WRONG_ANSWER,
            affected_scenarios=analysis.test_run.failed,
            fix_type=FixType.FINE_TUNING_DATA,
            title=f"{count} Training Pairs Available",
            problem=(
                "Your AI system made specific mistakes that can be "
                "corrected through targeted fine-tuning."
            ),
            suggested_fix=(
                f"Download {count} training pairs generated from your "
                f"actual failures. Each pair contains the problematic "
                f"input and the correct expected output. "
                f"Fine-tune your open-source model on these pairs to "
                f"correct the specific failure patterns found."
            ),
            implementation_steps=[
                "Download the JSONL training data from InspectAI",
                "Review pairs to confirm correct outputs are appropriate",
                "Fine-tune your model using standard SFT training",
                "Re-run InspectAI to verify improvement",
                "Repeat until pass rate reaches target",
            ],
            verification_scenarios=[
                "Run InspectAI again after fine-tuning",
                "Check if previously failing scenarios now pass",
            ],
            suggested_priority=Priority.MEDIUM,
            estimated_impact=(
                f"On-policy learning from {count} real failure cases "
                f"may significantly improve pass rate for open-source models"
            ),
            disclaimer=(
                "Fine-tuning is recommended only for open-source models "
                "you control. Review all training pairs before use. "
                "Results depend on your model architecture and training setup."
            ),
        )

    # ─── Private: improvement estimate ───────────────────────────

    async def _estimate_improvement(
        self,
        analysis: AnalysisResult,
        fixes: list[DetailedFixRecommendation],
        company_name: str,
    ) -> str:
        """
        Generates a human-readable improvement estimate.
        Honest about uncertainty — labeled as estimate only.
        """
        high_priority_fixes = [
            f for f in fixes if f.suggested_priority == Priority.HIGH
        ]
        high_priority_scenarios = sum(
            f.affected_scenarios for f in high_priority_fixes
        )
        total_failures = analysis.test_run.failed
        total_scenarios = analysis.test_run.total_scenarios

        if total_scenarios == 0:
            return "No scenarios tested."

        current_pass_rate = round(analysis.test_run.pass_rate * 100, 1)
        potential_fixes = min(high_priority_scenarios, total_failures)
        estimated_new_failures = max(0, total_failures - potential_fixes)
        estimated_new_pass_rate = round(
            ((total_scenarios - estimated_new_failures) / total_scenarios) * 100,
            1,
        )

        prompt = f"""Write a 2-sentence improvement estimate for {company_name}.

Current pass rate: {current_pass_rate}%
Fixes generated: {len(fixes)} ({len(high_priority_fixes)} high priority)
High priority fixes address: {high_priority_scenarios} of {total_failures} failures

Rules:
1. Be honest — use "may", "estimated", "could" — not guarantees
2. Mention implementing high priority fixes first
3. Keep it to 2 sentences maximum
4. Be specific about the numbers"""

        try:
            async with asyncio.timeout(LLM_TIMEOUT):
                response = await litellm.acompletion(
                    model=self.model,
                    messages=[{"role": "user", "content": prompt}],
                    temperature=0.2,
                    max_tokens=100,
                )

            if hasattr(response, "usage") and response.usage:
                tokens = response.usage.total_tokens or 0
                self._cost += (tokens / 1000) * COST_PER_1K_TOKENS

            return response.choices[0].message.content.strip()

        except Exception:
            return (
                f"Implementing {len(high_priority_fixes)} high priority fixes "
                f"may improve pass rate from {current_pass_rate}% to an "
                f"estimated {estimated_new_pass_rate}%. "
                f"Results depend on implementation quality."
            )
