"""
Failure analyzer for InspectAI.

Takes TestResult objects from the test runner and produces
a complete failure analysis using a four-step pipeline:

Step 1 — Count by failure type (pure Python, free, instant)
Step 2 — Embed + cluster with HDBSCAN (local model, free)
Step 3 — LLM labels each cluster with root cause
Step 4 — D5 contrast: compare failures vs successes

Output:
- TestRun object with full statistics
- List of FailurePattern objects with root causes
- Human readable insight summary

Embedding model: all-MiniLM-L6-v2 (local, 90MB, free forever)
Clustering: HDBSCAN (handles noise, no forced clusters)
"""

from __future__ import annotations

import asyncio
import json
from collections import Counter
from datetime import UTC, datetime
from uuid import uuid4

import litellm
import structlog
from pydantic import BaseModel, Field

from inspectai.config import settings
from inspectai.models.schemas import (
    FailureType,
    Priority,
    Scenario,
    SystemConfig,
    SystemType,
    TestResult,
    TestRun,
    TestRunConfig,
)

logger = structlog.get_logger()

# ─── Constants ────────────────────────────────────────────────────

EMBEDDING_MODEL = "all-MiniLM-L6-v2"
HDBSCAN_MIN_CLUSTER_SIZE = 3
HDBSCAN_MIN_SAMPLES = 2
LLM_TIMEOUT = 30
MIN_FAILURES_FOR_CLUSTERING = 5

DEFAULT_FAILURE_PRIORITY = {
    FailureType.POLICY_VIOLATION: Priority.HIGH,
    FailureType.ESCALATION_FAILURE: Priority.HIGH,
    FailureType.HALLUCINATION: Priority.HIGH,
    FailureType.WRONG_ANSWER: Priority.MEDIUM,
    FailureType.INCOMPLETE: Priority.MEDIUM,
    FailureType.CONTEXT_LOSS: Priority.LOW,
}


# ─── Result models ────────────────────────────────────────────────

class FailurePattern(BaseModel):
    """
    A cluster of similar failures with root cause analysis.
    Generated by the failure analyzer after clustering.
    """

    pattern_id: str = Field(default_factory=lambda: str(uuid4()))
    failure_type: FailureType
    scenario_count: int
    percentage_of_total_failures: float
    root_cause: str
    evidence: str
    example_inputs: list[str] = []
    immediate_fix: str
    suggested_priority: Priority
    company_priority: Priority | None = None
    cluster_label: str = ""
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(UTC)
    )


class AnalysisResult(BaseModel):
    """
    Complete output of the failure analyzer.
    """

    test_run: TestRun
    failure_patterns: list[FailurePattern] = []
    insight_summary: str = ""
    contrast_insights: str = ""
    total_clusters_found: int = 0
    noise_failures: int = 0
    analysis_cost_usd: float = 0.0


# ─── Main class ───────────────────────────────────────────────────

class FailureAnalyzer:
    """
    Analyzes test results to find failure patterns and root causes.

    Usage:
        analyzer = FailureAnalyzer()
        result = await analyzer.analyze(
            results=results,
            scenarios=scenarios,
            config=config,
            run_config=run_config,
        )
    """

    def __init__(self, model: str | None = None) -> None:
        self.model = model or settings.default_model
        self._embedding_model = None
        self._analysis_cost = 0.0

    def _get_embedding_model(self):
        """Lazy-loads sentence-transformers only when a test run actually needs it."""
        if self._embedding_model is None:
            from sentence_transformers import SentenceTransformer  # noqa: PLC0415
            logger.info("loading_embedding_model", model=EMBEDDING_MODEL)
            self._embedding_model = SentenceTransformer(EMBEDDING_MODEL)
            logger.info("embedding_model_loaded")
        return self._embedding_model

    async def analyze(
        self,
        results: list[TestResult],
        scenarios: list[Scenario] | None = None,
        config: SystemConfig | None = None,
        run_config: TestRunConfig | None = None,
        previous_run: TestRun | None = None,
    ) -> AnalysisResult:
        """
        Main entry point. Runs the four-step analysis pipeline.

        Steps:
        1. Count failures by type — pure Python stats
        2. Embed and cluster failures — local HDBSCAN
        3. LLM labels each cluster — root cause analysis
        4. D5 contrast — failures vs successes comparison
        5. Build TestRun and AnalysisResult
        """
        if not results:
            logger.warning("no_results_to_analyze")
            return self._empty_result(config)

        self._analysis_cost = 0.0

        logger.info(
            "analysis_started",
            total_results=len(results),
            failed=sum(1 for r in results if not r.passed),
            passed=sum(1 for r in results if r.passed),
        )

        # Step 1 — Count statistics
        stats = self._calculate_statistics(results)

        logger.info(
            "statistics_calculated",
            pass_rate=stats["pass_rate"],
            failure_breakdown=stats["failure_breakdown"],
        )

        # Step 2 — Embed and cluster failures
        failed_results = [r for r in results if not r.passed]
        clusters: dict[int, list[TestResult]] = {}

        if len(failed_results) >= MIN_FAILURES_FOR_CLUSTERING:
            clusters = await self._embed_and_cluster(failed_results)
            logger.info(
                "clustering_complete",
                clusters_found=len(clusters),
                noise_count=len(clusters.get(-1, [])),
            )
        else:
            logger.info(
                "too_few_failures_for_clustering",
                count=len(failed_results),
                minimum=MIN_FAILURES_FOR_CLUSTERING,
            )

        # Step 3 — LLM labels each cluster
        failure_patterns = await self._label_clusters(
            clusters=clusters,
            failed_results=failed_results,
            config=config,
            stats=stats,
        )

        # Step 4 — D5 contrast analysis
        contrast_insights = ""
        if failed_results and len(results) > len(failed_results):
            passed_results = [r for r in results if r.passed]
            contrast_insights = await self._d5_contrast(
                failed_results=failed_results,
                passed_results=passed_results,
                config=config,
            )

        # Step 5 — Generate insight summary
        insight_summary = await self._generate_insight_summary(
            stats=stats,
            failure_patterns=failure_patterns,
            contrast_insights=contrast_insights,
            config=config,
            previous_run=previous_run,
        )

        system_type = (
            config.system_type
            if config
            else (results[0].system_type if results else SystemType.CUSTOMER_SUPPORT)
        )

        test_run = TestRun(
            id=uuid4(),
            system_type=system_type,
            total_scenarios=len(results),
            passed=stats["passed_count"],
            failed=stats["failed_count"],
            failure_breakdown=stats["failure_breakdown"],
            pass_rate=stats["pass_rate"],
            started_at=datetime.now(UTC),
            completed_at=datetime.now(UTC),
            dry_run=run_config.dry_run if run_config else False,
            actual_cost_usd=self._analysis_cost,
        )

        noise_count = len(clusters.get(-1, [])) if clusters else 0

        analysis_result = AnalysisResult(
            test_run=test_run,
            failure_patterns=failure_patterns,
            insight_summary=insight_summary,
            contrast_insights=contrast_insights,
            total_clusters_found=max(
                0, len(clusters) - (1 if -1 in clusters else 0)
            ),
            noise_failures=noise_count,
            analysis_cost_usd=self._analysis_cost,
        )

        logger.info(
            "analysis_complete",
            patterns_found=len(failure_patterns),
            insight_length=len(insight_summary),
            cost=self._analysis_cost,
        )

        return analysis_result

    # ─── Private: statistics ──────────────────────────────────────

    def _calculate_statistics(self, results: list[TestResult]) -> dict:
        """
        Pure Python statistics. No LLM. No cost.
        """
        total = len(results)
        passed = sum(1 for r in results if r.passed)
        failed = total - passed

        failure_breakdown: dict[str, int] = dict(
            Counter(
                r.failure_type.value
                for r in results
                if not r.passed and r.failure_type
            )
        )

        avg_latency = (
            sum(r.latency_ms for r in results) / total if total > 0 else 0.0
        )
        avg_confidence = (
            sum(r.confidence_score for r in results) / total if total > 0 else 0.0
        )

        return {
            "total": total,
            "passed_count": passed,
            "failed_count": failed,
            "pass_rate": round(passed / total, 4) if total > 0 else 0.0,
            "failure_breakdown": failure_breakdown,
            "avg_latency_ms": round(avg_latency, 2),
            "avg_confidence": round(avg_confidence, 4),
        }

    # ─── Private: embed and cluster ───────────────────────────────

    async def _embed_and_cluster(
        self,
        failed_results: list[TestResult],
    ) -> dict[int, list[TestResult]]:
        """
        Embeds failed responses with sentence-transformers, clusters with HDBSCAN.
        Runs in executor to avoid blocking the async loop.
        Cluster -1 = noise (unique failures that don't fit any pattern).
        """
        loop = asyncio.get_event_loop()

        def _sync() -> dict[int, list[TestResult]]:
            model = self._get_embedding_model()
            texts = [r.actual_response for r in failed_results]

            logger.info(
                "embedding_failures",
                count=len(texts),
                model=EMBEDDING_MODEL,
            )

            embeddings = model.encode(
                texts,
                show_progress_bar=False,
                batch_size=32,
            )

            import hdbscan  # noqa: PLC0415
            clusterer = hdbscan.HDBSCAN(
                min_cluster_size=HDBSCAN_MIN_CLUSTER_SIZE,
                min_samples=HDBSCAN_MIN_SAMPLES,
                metric="euclidean",
                cluster_selection_method="eom",
            )
            labels = clusterer.fit_predict(embeddings)

            clusters: dict[int, list[TestResult]] = {}
            for result, label in zip(failed_results, labels):
                label_int = int(label)
                if label_int not in clusters:
                    clusters[label_int] = []
                clusters[label_int].append(result)

            return clusters

        return await loop.run_in_executor(None, _sync)

    # ─── Private: label clusters ──────────────────────────────────

    async def _label_clusters(
        self,
        clusters: dict[int, list[TestResult]],
        failed_results: list[TestResult],
        config: SystemConfig | None,
        stats: dict,
    ) -> list[FailurePattern]:
        """
        LLM labels each real cluster. Groups noise by failure type.
        """
        patterns: list[FailurePattern] = []
        company_name = "the company"
        if config:
            active = config.get_active_config()
            if active:
                company_name = getattr(active, "company_name", "the company")

        total_failures = len(failed_results)

        for cluster_id, cluster_results in clusters.items():
            if cluster_id == -1:
                continue
            pattern = await self._label_single_cluster(
                cluster_id=cluster_id,
                cluster_results=cluster_results,
                total_failures=total_failures,
                company_name=company_name,
            )
            if pattern:
                patterns.append(pattern)

        # Noise cluster — group by failure type as fallback
        noise_results = clusters.get(-1, [])
        if noise_results:
            by_type: dict[str, list[TestResult]] = {}
            for r in noise_results:
                key = r.failure_type.value if r.failure_type else "UNKNOWN"
                by_type.setdefault(key, []).append(r)

            for failure_type_str, type_results in by_type.items():
                try:
                    failure_type = FailureType(failure_type_str)
                except ValueError:
                    failure_type = FailureType.WRONG_ANSWER

                patterns.append(
                    FailurePattern(
                        failure_type=failure_type,
                        scenario_count=len(type_results),
                        percentage_of_total_failures=round(
                            len(type_results) / total_failures * 100, 1
                        ),
                        root_cause=(
                            f"Isolated {failure_type_str} failures — unique cases"
                        ),
                        evidence=f"{len(type_results)} individual failures of this type",
                        example_inputs=[
                            r.actual_response[:100] for r in type_results[:3]
                        ],
                        immediate_fix=(
                            "Review individual cases — no common pattern detected"
                        ),
                        suggested_priority=DEFAULT_FAILURE_PRIORITY.get(
                            failure_type, Priority.MEDIUM
                        ),
                        cluster_label="noise",
                    )
                )

        # No clusters at all — label by failure type directly
        if not clusters and failed_results:
            patterns = await self._label_without_clustering(
                failed_results=failed_results,
                total_failures=total_failures,
                company_name=company_name,
            )

        patterns.sort(key=lambda p: p.scenario_count, reverse=True)
        return patterns

    async def _label_single_cluster(
        self,
        cluster_id: int,
        cluster_results: list[TestResult],
        total_failures: int,
        company_name: str,
    ) -> FailurePattern | None:
        """
        Calls LLM to label a single cluster with root cause.
        """
        dominant = Counter(
            r.failure_type.value for r in cluster_results if r.failure_type
        ).most_common(1)
        failure_type_str = dominant[0][0] if dominant else "WRONG_ANSWER"
        try:
            failure_type = FailureType(failure_type_str)
        except ValueError:
            failure_type = FailureType.WRONG_ANSWER

        examples = "\n".join([
            f"- Input: {r.actual_response[:150]}" for r in cluster_results[:5]
        ])

        prompt = f"""You are analyzing a cluster of similar AI failures for {company_name}.

CLUSTER SIZE: {len(cluster_results)} failures
DOMINANT FAILURE TYPE: {failure_type_str}
PERCENTAGE OF ALL FAILURES: {round(len(cluster_results) / total_failures * 100, 1)}%

EXAMPLE FAILURES FROM THIS CLUSTER:
{examples}

Analyze this cluster and provide:
1. ROOT CAUSE: What is the underlying reason these failures share a pattern?
2. EVIDENCE: What specific evidence in the responses supports this root cause?
3. IMMEDIATE FIX: One specific, actionable fix (prompt change, guardrail, or policy)
4. CLUSTER LABEL: A short 3-5 word label for this failure pattern

Return ONLY valid JSON:
{{
  "root_cause": "specific root cause explanation",
  "evidence": "specific evidence from the responses",
  "immediate_fix": "one actionable fix",
  "cluster_label": "short descriptive label"
}}"""

        try:
            async with asyncio.timeout(LLM_TIMEOUT):
                response = await litellm.acompletion(
                    model=self.model,
                    messages=[{"role": "user", "content": prompt}],
                    temperature=0.2,
                    max_tokens=400,
                )

            raw = response.choices[0].message.content.strip()
            if raw.startswith("```"):
                raw = raw.split("```")[1]
                if raw.startswith("json"):
                    raw = raw[4:]
            data = json.loads(raw.strip())

            if hasattr(response, "usage") and response.usage:
                tokens = response.usage.total_tokens or 0
                self._analysis_cost += (tokens / 1000) * 0.003

            return FailurePattern(
                failure_type=failure_type,
                scenario_count=len(cluster_results),
                percentage_of_total_failures=round(
                    len(cluster_results) / total_failures * 100, 1
                ),
                root_cause=data.get("root_cause", "Unknown root cause"),
                evidence=data.get("evidence", ""),
                example_inputs=[
                    r.actual_response[:100] for r in cluster_results[:3]
                ],
                immediate_fix=data.get("immediate_fix", "Review manually"),
                suggested_priority=DEFAULT_FAILURE_PRIORITY.get(
                    failure_type, Priority.MEDIUM
                ),
                cluster_label=data.get("cluster_label", f"cluster_{cluster_id}"),
            )

        except Exception as e:
            logger.error(
                "cluster_labeling_failed",
                cluster_id=cluster_id,
                error=str(e),
            )
            return FailurePattern(
                failure_type=failure_type,
                scenario_count=len(cluster_results),
                percentage_of_total_failures=round(
                    len(cluster_results) / total_failures * 100, 1
                ),
                root_cause="Analysis failed — review manually",
                evidence="",
                example_inputs=[
                    r.actual_response[:100] for r in cluster_results[:3]
                ],
                immediate_fix="Manual review required",
                suggested_priority=DEFAULT_FAILURE_PRIORITY.get(
                    failure_type, Priority.MEDIUM
                ),
                cluster_label=f"cluster_{cluster_id}",
            )

    async def _label_without_clustering(
        self,
        failed_results: list[TestResult],
        total_failures: int,
        company_name: str,
    ) -> list[FailurePattern]:
        """
        Fallback when clustering is not possible — groups by failure type.
        """
        by_type: dict[str, list[TestResult]] = {}
        for r in failed_results:
            key = r.failure_type.value if r.failure_type else "UNKNOWN"
            by_type.setdefault(key, []).append(r)

        patterns = []
        for failure_type_str, type_results in by_type.items():
            pattern = await self._label_single_cluster(
                cluster_id=hash(failure_type_str),
                cluster_results=type_results,
                total_failures=total_failures,
                company_name=company_name,
            )
            if pattern:
                patterns.append(pattern)
        return patterns

    # ─── Private: D5 contrast ─────────────────────────────────────

    async def _d5_contrast(
        self,
        failed_results: list[TestResult],
        passed_results: list[TestResult],
        config: SystemConfig | None,
    ) -> str:
        """
        Contrastive pattern detection — failures vs successes.
        """
        company_name = "the company"
        if config:
            active = config.get_active_config()
            if active:
                company_name = getattr(active, "company_name", "the company")

        failed_text = "\n".join([
            f"- {r.actual_response[:100]}" for r in failed_results[:10]
        ])
        passed_text = "\n".join([
            f"- {r.actual_response[:100]}" for r in passed_results[:10]
        ])

        prompt = f"""You are doing contrastive failure analysis for {company_name}.

Compare these FAILED AI responses vs SUCCESSFUL AI responses.
Find what distinguishes the failures from the successes.

FAILED RESPONSES (sample of {min(len(failed_results), 10)}):
{failed_text}

SUCCESSFUL RESPONSES (sample of {min(len(passed_results), 10)}):
{passed_text}

What patterns distinguish the failures from the successes?
Focus on:
- What the failing responses have in common
- What the successful responses do that failing ones don't
- The root behavioral difference

Write 2-3 sentences of specific, actionable insight.
No bullet points. Plain prose. Be specific."""

        try:
            async with asyncio.timeout(LLM_TIMEOUT):
                response = await litellm.acompletion(
                    model=self.model,
                    messages=[{"role": "user", "content": prompt}],
                    temperature=0.2,
                    max_tokens=200,
                )

            if hasattr(response, "usage") and response.usage:
                tokens = response.usage.total_tokens or 0
                self._analysis_cost += (tokens / 1000) * 0.003

            return response.choices[0].message.content.strip()

        except Exception as e:
            logger.error("d5_contrast_failed", error=str(e))
            return ""

    # ─── Private: insight summary ─────────────────────────────────

    async def _generate_insight_summary(
        self,
        stats: dict,
        failure_patterns: list[FailurePattern],
        contrast_insights: str,
        config: SystemConfig | None,
        previous_run: TestRun | None,
    ) -> str:
        """
        Generates an executive summary. Includes trend if previous run provided.
        """
        company_name = "the system"
        if config:
            active = config.get_active_config()
            if active:
                company_name = getattr(active, "company_name", "the system")

        patterns_text = "\n".join([
            f"- {p.cluster_label}: {p.scenario_count} failures "
            f"({p.percentage_of_total_failures}%) — {p.root_cause[:80]}"
            for p in failure_patterns[:5]
        ])

        trend_text = ""
        if previous_run:
            delta = stats["pass_rate"] - previous_run.pass_rate
            direction = "improved" if delta > 0 else "declined"
            trend_text = (
                f"\nTREND: Pass rate {direction} by "
                f"{abs(round(delta * 100, 1))}% vs previous run "
                f"({round(previous_run.pass_rate * 100, 1)}% → "
                f"{round(stats['pass_rate'] * 100, 1)}%)"
            )

        prompt = f"""Write an executive summary for {company_name}'s AI test results.

RESULTS:
- Pass rate: {round(stats['pass_rate'] * 100, 1)}%
- Total tested: {stats['total']} scenarios
- Passed: {stats['passed_count']}
- Failed: {stats['failed_count']}
{trend_text}

TOP FAILURE PATTERNS:
{patterns_text if patterns_text else "No significant patterns detected"}

CONTRAST INSIGHT:
{contrast_insights if contrast_insights else "Not available"}

Write 3-4 sentences. Be specific and actionable.
Tell the company exactly what is broken and what to fix first.
No bullet points. Plain prose."""

        try:
            async with asyncio.timeout(LLM_TIMEOUT):
                response = await litellm.acompletion(
                    model=self.model,
                    messages=[{"role": "user", "content": prompt}],
                    temperature=0.2,
                    max_tokens=250,
                )

            if hasattr(response, "usage") and response.usage:
                tokens = response.usage.total_tokens or 0
                self._analysis_cost += (tokens / 1000) * 0.003

            return response.choices[0].message.content.strip()

        except Exception as e:
            logger.error("insight_summary_failed", error=str(e))
            return (
                f"Analysis complete. Pass rate: "
                f"{round(stats['pass_rate'] * 100, 1)}%. "
                f"{stats['failed_count']} failures detected across "
                f"{len(failure_patterns)} patterns."
            )

    # ─── Private: empty result ────────────────────────────────────

    def _empty_result(self, config: SystemConfig | None) -> AnalysisResult:
        system_type = (
            config.system_type if config else SystemType.CUSTOMER_SUPPORT
        )
        return AnalysisResult(
            test_run=TestRun(
                id=uuid4(),
                system_type=system_type,
                total_scenarios=0,
                passed=0,
                failed=0,
                failure_breakdown={},
                pass_rate=0.0,
                started_at=datetime.now(UTC),
                completed_at=datetime.now(UTC),
            )
        )
