const { PageHeader, gradeFromPassRate, formatRelativeTime } = window.Shared;

function Reports({ runs, currentRun, onNavigate }) {
  const completed = runs.filter(r => r.status === 'completed');
  const latest = completed[0];

  async function downloadReport(run) {
    const full = run.results_json ? run : await window.API.getRun(run.id);
    if (!full) return;
    const analysis = full.analysis_json;
    const fixes = full.fixes_json;
    const grade = gradeFromPassRate(run.pass_rate);

    const report = {
      title: `InspectAI Quality Report — ${full.company_name}`,
      generated_at: new Date().toISOString(),
      monitoring_cycle: full.created_at,
      quality_grade: grade.letter,
      pass_rate: `${Math.round((full.pass_rate || 0) * 100)}%`,
      scenarios_monitored: full.total_scenarios,
      open_issues: full.total_failures,
      deployment_verdict: (full.pass_rate >= 0.8 && full.total_failures < 10) ? 'SAFE TO DEPLOY' : 'FIX BEFORE DEPLOY',
      issue_summary: analysis?.insight_summary || '',
      failure_patterns: analysis?.failure_patterns?.map(p => ({
        type: p.failure_type,
        count: p.scenario_count,
        root_cause: p.root_cause,
        priority: p.suggested_priority,
      })) || [],
      remediation_actions: fixes?.fixes?.map(f => ({
        title: f.title,
        priority: f.suggested_priority,
        type: f.fix_type,
        problem: f.problem,
        suggested_fix: f.suggested_fix,
      })) || [],
      disclaimer: 'Generated by InspectAI continuous monitoring. Review all recommendations before implementing.',
    };

    const blob = new Blob([JSON.stringify(report, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `inspectai_report_${full.id}_${new Date().toISOString().slice(0, 10)}.json`;
    a.click();
    URL.revokeObjectURL(url);
  }

  function downloadExecutiveSummary(run) {
    const grade = gradeFromPassRate(run.pass_rate);
    const pr = Math.round((run.pass_rate || 0) * 100);
    const fixes = run.fixes_json || currentRun?.fixes_json;
    const highCount = fixes?.fixes?.filter(f => f.suggested_priority === 'HIGH').length || 0;

    const text = [
      `INSPECTAI EXECUTIVE SUMMARY`,
      `Organization: ${run.company_name}`,
      `Report Date: ${new Date().toLocaleDateString()}`,
      `Monitoring Cycle: ${formatRelativeTime(run.created_at)}`,
      ``,
      `QUALITY GRADE: ${grade.letter} (${pr}%)`,
      `Scenarios Monitored: ${run.total_scenarios}`,
      `Open Issues: ${run.total_failures}`,
      `High Priority Actions: ${highCount}`,
      ``,
      `DEPLOYMENT VERDICT: ${pr >= 80 && run.total_failures < 10 ? 'SAFE TO DEPLOY' : 'FIX BEFORE DEPLOY'}`,
      ``,
      `InspectAI runs continuously inside your chatbot to detect policy violations,`,
      `hallucinations, and escalation failures before customers are impacted.`,
      ``,
      `For full technical details, download the complete quality report.`,
    ].join('\n');

    const blob = new Blob([text], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `inspectai_executive_${run.company_name.replace(/\s+/g, '_')}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  }

  return (
    <div className="page-scroll">
      <PageHeader
        title="Reports"
        subtitle="Quality and compliance reports for stakeholders"
      />

      {completed.length === 0 ? (
        <div className="card" style={{ textAlign: 'center', padding: '48px' }}>
          <div style={{ fontSize: '40px', marginBottom: '12px' }}>📄</div>
          <p style={{ color: '#64748B' }}>Reports will be available after your first monitoring cycle completes.</p>
        </div>
      ) : (
        <>
          {/* Latest report highlight */}
          {latest && (
            <div className="card" style={{
              marginBottom: '20px',
              background: 'linear-gradient(135deg, #EEF2FF 0%, #FFFFFF 60%)',
              borderColor: '#C7D2FE',
            }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', flexWrap: 'wrap', gap: '16px' }}>
                <div>
                  <div style={{ fontSize: '11px', fontWeight: '600', color: '#6366F1', textTransform: 'uppercase', letterSpacing: '0.6px', marginBottom: '8px' }}>
                    Latest Report
                  </div>
                  <div style={{ fontSize: '18px', fontWeight: '700', color: '#0F172A', marginBottom: '4px' }}>
                    {latest.company_name} — Quality Assessment
                  </div>
                  <div style={{ fontSize: '13px', color: '#64748B' }}>
                    Grade {gradeFromPassRate(latest.pass_rate).letter} · {Math.round((latest.pass_rate || 0) * 100)}% · {formatRelativeTime(latest.created_at)}
                  </div>
                </div>
                <div style={{ display: 'flex', gap: '8px', flexWrap: 'wrap' }}>
                  <button onClick={() => downloadExecutiveSummary(latest)} style={{
                    padding: '9px 16px', background: '#FFFFFF', border: '1px solid #E2E8F0',
                    borderRadius: '8px', fontSize: '13px', fontWeight: '600', color: '#475569',
                  }}>
                    Executive Summary (.txt)
                  </button>
                  <button onClick={() => downloadReport(latest)} style={{
                    padding: '9px 16px', background: '#4F46E5', color: '#fff',
                    borderRadius: '8px', fontSize: '13px', fontWeight: '600',
                  }}>
                    Full Report (.json)
                  </button>
                </div>
              </div>
            </div>
          )}

          {/* Report types info */}
          <div className="grid g-3" style={{ marginBottom: '24px' }}>
            {[
              { title: 'Executive Summary', desc: 'One-page overview for leadership and compliance teams. Pass rate, grade, and deployment verdict.', icon: '📊' },
              { title: 'Technical Report', desc: 'Full issue breakdown, root causes, failure patterns, and remediation actions for engineering teams.', icon: '🔧' },
              { title: 'Audit Trail', desc: 'Historical monitoring cycles with trend data for regression tracking and compliance documentation.', icon: '📋' },
            ].map(r => (
              <div key={r.title} className="card">
                <div style={{ fontSize: '24px', marginBottom: '10px' }}>{r.icon}</div>
                <div style={{ fontSize: '14px', fontWeight: '700', color: '#0F172A', marginBottom: '6px' }}>{r.title}</div>
                <div style={{ fontSize: '13px', color: '#64748B', lineHeight: '1.5' }}>{r.desc}</div>
              </div>
            ))}
          </div>

          {/* Historical reports */}
          <div className="card">
            <div style={{ fontSize: '13px', fontWeight: '700', color: '#0F172A', marginBottom: '14px' }}>
              Report History
            </div>
            {completed.map((run, i) => {
              const g = gradeFromPassRate(run.pass_rate);
              return (
                <div key={run.id} style={{
                  display: 'flex', alignItems: 'center', gap: '14px', padding: '12px 0',
                  borderBottom: i < completed.length - 1 ? '1px solid #F1F5F9' : 'none',
                }}>
                  <div style={{
                    width: '40px', height: '40px', borderRadius: '8px',
                    background: `${g.color}12`, border: `1px solid ${g.color}30`,
                    display: 'flex', alignItems: 'center', justifyContent: 'center',
                    fontWeight: '800', color: g.color,
                  }}>{g.letter}</div>
                  <div style={{ flex: 1 }}>
                    <div style={{ fontSize: '13px', fontWeight: '600', color: '#0F172A' }}>
                      Quality Report — {run.total_scenarios} scenarios
                    </div>
                    <div style={{ fontSize: '12px', color: '#94A3B8' }}>{formatRelativeTime(run.created_at)}</div>
                  </div>
                  <div style={{ fontSize: '14px', fontWeight: '700', color: g.color, fontFamily: 'JetBrains Mono, monospace', marginRight: '8px' }}>
                    {Math.round((run.pass_rate || 0) * 100)}%
                  </div>
                  <button onClick={() => downloadReport(run)} style={{
                    padding: '6px 12px', background: '#F1F5F9', borderRadius: '6px',
                    fontSize: '12px', color: '#475569', fontWeight: '600',
                  }}>Download</button>
                </div>
              );
            })}
          </div>
        </>
      )}
    </div>
  );
}

window.Reports = Reports;
